# Generated by Django 5.1.2 on 2024-10-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='productdate',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='car',
            name='product_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
